theme: jekyll-theme-leap-day
title: "Data Science And Machine Learning"
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: dc-aichara
  instagram: dcaichara
  linkedin: 
  pinterest: 
  twitter: dcaichara

