theme: jekyll-theme-leap-day
title: "Data Science And Machine Learning"
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: dc-aichara
  instagram: dcaichara
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: dcaichara
stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
