theme: jekyll-theme-leap-day
title: "Data Science And Machine Learning"
footer-links:
  twitter_username: dc_aichara
  github_username:  dc-aichara
  linkedin_username: dcaichara
  instagram_username: dcaichara




